export interface CharacterProfile {
  id: number;
  name: string;
  role: string;
  mood: string;
  iq: string;
  avatar?: string; // Optional custom avatar URL
}

export const CHARACTERS: CharacterProfile[] = [
  { id: 1, name: "Albert Einstein", role: "Physicist", mood: "Curious, contemplative", iq: "160" },
  { id: 2, name: "Isaac Newton", role: "Physicist/Mathematician", mood: "Obsessive, solitary", iq: "190" },
  { id: 3, name: "Nikola Tesla", role: "Inventor", mood: "Eccentric, obsessive", iq: "160-200" },
  { id: 4, name: "Marie Curie", role: "Chemist/Physicist", mood: "Determined, calm", iq: "180" },
  { id: 5, name: "Richard Feynman", role: "Physicist", mood: "Playful, irreverent", iq: "125" },
  { id: 6, name: "Stephen Hawking", role: "Theoretical Physicist", mood: "Resilient, analytical", iq: "160" },
  { id: 7, name: "Ada Lovelace", role: "Mathematician/Programmer", mood: "Imaginative, focused", iq: "180" },
  { id: 8, name: "Alan Turing", role: "Mathematician/Computer Scientist", mood: "Intense, private", iq: "185" },
  { id: 9, name: "Leonardo da Vinci", role: "Artist/Inventor", mood: "Curious, restless", iq: "180-190" },
  { id: 10, name: "Galileo Galilei", role: "Astronomer", mood: "Bold, determined", iq: "160" },
  { id: 11, name: "Carl Sagan", role: "Astronomer/Science Communicator", mood: "Wonder-driven, warm", iq: "150" },
  { id: 12, name: "Katherine Johnson", role: "Mathematician/NASA", mood: "Precise, disciplined", iq: "160" },
  { id: 13, name: "Elon Musk", role: "Entrepreneur/Engineer", mood: "Obsessive, aggressive", iq: "155" },
  { id: 14, name: "Jeff Bezos", role: "Entrepreneur", mood: "Calculated, cold", iq: "145" },
  { id: 15, name: "Bill Gates", role: "Entrepreneur/Philanthropist", mood: "Analytical, competitive", iq: "150" },
  { id: 16, name: "Mark Zuckerberg", role: "Entrepreneur", mood: "Focused, analytical", iq: "152" },
  { id: 17, name: "Thomas Edison", role: "Inventor", mood: "Persistent, impatient", iq: "145" },
  { id: 18, name: "Nikola Kopernik (Copernicus)", role: "Astronomer", mood: "Thoughtful, meticulous", iq: "160" },
  { id: 19, name: "Benjamin Franklin", role: "Polymath", mood: "Curious, pragmatic", iq: "160" },
  { id: 20, name: "Charles Darwin", role: "Naturalist", mood: "Patient, contemplative", iq: "165" },
  { id: 21, name: "Sigmund Freud", role: "Neurologist/Psychologist", mood: "Introspective, analytical", iq: "155" },
  { id: 22, name: "Noam Chomsky", role: "Linguist/Philosopher", mood: "Critical, sharp", iq: "160" },
  { id: 23, name: "James Clerk Maxwell", role: "Physicist", mood: "Deeply analytical", iq: "170" },
  { id: 24, name: "Richard Dawkins", role: "Biologist/Author", mood: "Rational, sharp-tongued", iq: "145" },
  { id: 25, name: "Rosalind Franklin", role: "Chemist", mood: "Diligent, private", iq: "150" },
  { id: 26, name: "Alexander Graham Bell", role: "Inventor", mood: "Curious, practical", iq: "150" },
  { id: 27, name: "Wright Brothers", role: "Inventors", mood: "Persistent, meticulous", iq: "140-150" },
  { id: 28, name: "Steve Jobs", role: "Entrepreneur", mood: "Visionary, temperamental", iq: "145" },
  { id: 29, name: "Oprah Winfrey", role: "Media Mogul", mood: "Warm, driven", iq: "140" },
  { id: 30, name: "Serena Williams", role: "Athlete", mood: "Aggressive, determined", iq: "130" },
  { id: 31, name: "Michael Jordan", role: "Athlete", mood: "Competitive, focused", iq: "145" },
  { id: 32, name: "Usain Bolt", role: "Athlete", mood: "Confident, playful", iq: "130" },
  { id: 33, name: "Muhammad Ali", role: "Athlete", mood: "Confident, strategic", iq: "145" },
  { id: 34, name: "Neil Armstrong", role: "Astronaut", mood: "Calm, precise", iq: "145" },
  { id: 35, name: "Buzz Aldrin", role: "Astronaut", mood: "Focused, brave", iq: "145" },
  { id: 36, name: "Yuri Gagarin", role: "Cosmonaut", mood: "Courageous, charismatic", iq: "140" },
  { id: 37, name: "Elon Musk’s engineers (generic)", role: "Engineer", mood: "Problem-focused, obsessive", iq: "130-150" },
  { id: 38, name: "Factory worker (generic)", role: "Laborer", mood: "Tired, disciplined", iq: "90-110" },
  { id: 39, name: "Teacher (generic)", role: "Educator", mood: "Patient, resilient", iq: "110-130" },
  { id: 40, name: "Farmer (generic)", role: "Agriculture", mood: "Practical, persistent", iq: "90-110" },
  { id: 41, name: "Florence Nightingale", role: "Nurse", mood: "Compassionate, determined", iq: "140" },
  { id: 42, name: "Mother Teresa", role: "Humanitarian", mood: "Compassionate, patient", iq: "140" },
  { id: 43, name: "Malala Yousafzai", role: "Activist", mood: "Courageous, determined", iq: "140" },
  { id: 44, name: "Greta Thunberg", role: "Activist", mood: "Stern, relentless", iq: "145" },
  { id: 45, name: "Martin Luther King Jr.", role: "Civil Rights Leader", mood: "Charismatic, hopeful", iq: "140" },
  { id: 46, name: "Nelson Mandela", role: "Statesman", mood: "Resilient, strategic", iq: "145" },
  { id: 47, name: "Winston Churchill", role: "Politician", mood: "Witty, stubborn", iq: "140" },
  { id: 48, name: "Abraham Lincoln", role: "Politician", mood: "Thoughtful, determined", iq: "160" },
  { id: 49, name: "Mahatma Gandhi", role: "Activist", mood: "Calm, principled", iq: "140" },
  { id: 50, name: "Confucius", role: "Philosopher", mood: "Reflective, disciplined", iq: "160" },
  { id: 51, name: "Socrates", role: "Philosopher", mood: "Questioning, sharp", iq: "165" },
  { id: 52, name: "Plato", role: "Philosopher", mood: "Analytical, visionary", iq: "170" },
  { id: 53, name: "Aristotle", role: "Philosopher", mood: "Systematic, curious", iq: "180" },
  { id: 54, name: "Sun Tzu", role: "Strategist", mood: "Calculated, observant", iq: "150" },
  { id: 55, name: "Genghis Khan", role: "Conqueror", mood: "Aggressive, strategic", iq: "140" },
  { id: 56, name: "Alexander the Great", role: "Conqueror", mood: "Ambitious, bold", iq: "155" },
  { id: 57, name: "Cleopatra", role: "Monarch", mood: "Intelligent, political", iq: "140" },
  { id: 58, name: "Queen Elizabeth I", role: "Monarch", mood: "Strategic, calculating", iq: "155" },
  { id: 59, name: "Marie Antoinette", role: "Monarch", mood: "Luxurious, playful", iq: "120" },
  { id: 60, name: "Elon Musk (again for clarity)", role: "Entrepreneur", mood: "Obsessive, visionary", iq: "155" },
  { id: 61, name: "Jeff Bezos", role: "Entrepreneur", mood: "Analytical, disciplined", iq: "145" },
  { id: 62, name: "Warren Buffett", role: "Investor", mood: "Calm, patient", iq: "155" },
  { id: 63, name: "Charlie Munger", role: "Investor", mood: "Rational, witty", iq: "160" },
  { id: 64, name: "Mark Cuban", role: "Entrepreneur", mood: "Aggressive, opportunistic", iq: "145" },
  { id: 65, name: "Larry Page", role: "Entrepreneur", mood: "Analytical, focused", iq: "155" },
  { id: 66, name: "Sergey Brin", role: "Entrepreneur", mood: "Curious, analytical", iq: "155" },
  { id: 67, name: "Tim Cook", role: "CEO", mood: "Calm, strategic", iq: "140" },
  { id: 68, name: "Sundar Pichai", role: "CEO", mood: "Thoughtful, disciplined", iq: "145" },
  { id: 69, name: "Satya Nadella", role: "CEO", mood: "Analytical, empathetic", iq: "150" },
  { id: 70, name: "Bill Nye", role: "Science Communicator", mood: "Curious, playful", iq: "130" },
  { id: 71, name: "Elon Musk engineer team", role: "Engineers", mood: "Problem-solving, intense", iq: "140-150" },
  { id: 72, name: "Nikola Tesla lab assistant", role: "Assistant", mood: "Obedient, curious", iq: "130-140" },
  { id: 73, name: "Factory supervisor", role: "Worker", mood: "Bossy, disciplined", iq: "120" },
  { id: 74, name: "Waiter/waitress", role: "Worker", mood: "Friendly, tired", iq: "95-110" },
  { id: 75, name: "Janitor", role: "Worker", mood: "Steady, patient", iq: "90-100" },
  { id: 76, name: "Artist (generic)", role: "Creative", mood: "Emotional, passionate", iq: "120-140" },
  { id: 77, name: "Vincent van Gogh", role: "Painter", mood: "Passionate, unstable", iq: "140" },
  { id: 78, name: "Pablo Picasso", role: "Painter", mood: "Bold, playful", iq: "145" },
  { id: 79, name: "Frida Kahlo", role: "Painter", mood: "Emotional, resilient", iq: "135" },
  { id: 80, name: "Michelangelo", role: "Sculptor/Painter", mood: "Perfectionist, intense", iq: "150" },
  { id: 81, name: "Beethoven", role: "Composer", mood: "Intense, visionary", iq: "140" },
  { id: 82, name: "Mozart", role: "Composer", mood: "Playful, genius", iq: "150" },
  { id: 83, name: "Chopin", role: "Composer", mood: "Sensitive, focused", iq: "140" },
  { id: 84, name: "Elon Musk SpaceX engineer", role: "Engineer", mood: "Problem-focused, obsessive", iq: "145" },
  { id: 85, name: "NASA Mission Control", role: "Team", mood: "Alert, disciplined", iq: "130-140" },
  { id: 86, name: "Airline pilot", role: "Professional", mood: "Calm, precise", iq: "135" },
  { id: 87, name: "Surgeon", role: "Professional", mood: "Focused, calm", iq: "145" },
  { id: 88, name: "Firefighter", role: "Worker", mood: "Brave, determined", iq: "110-130" },
  { id: 89, name: "Police Officer", role: "Worker", mood: "Alert, disciplined", iq: "110-130" },
  { id: 90, name: "Lawyer", role: "Professional", mood: "Strategic, analytical", iq: "140" },
  { id: 91, name: "Judge", role: "Professional", mood: "Calm, fair", iq: "140" },
  { id: 92, name: "Chef", role: "Professional", mood: "Creative, precise", iq: "120-135" },
  { id: 93, name: "Elon Musk Tesla engineer", role: "Engineer", mood: "Problem-solving, obsessive", iq: "145" },
  { id: 94, name: "Construction worker", role: "Labor", mood: "Physical, steady", iq: "90-110" },
  { id: 95, name: "Miner", role: "Labor", mood: "Resilient, tired", iq: "85-100" },
  { id: 96, name: "Driver", role: "Worker", mood: "Alert, patient", iq: "90-110" },
  { id: 97, name: "Elon Musk AI engineer", role: "Engineer", mood: "Analytical, obsessive", iq: "150" },
  { id: 98, name: "Hacker (ethical)", role: "Specialist", mood: "Curious, intense", iq: "140-155" },
  { id: 99, name: "Internet pioneer", role: "Innovator", mood: "Visionary, obsessive", iq: "150" },
  { id: 100, name: "Random high-IQ person", role: "General", mood: "Curious, obsessive", iq: "160" }
];
